# dynamic configuration
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
       # Recommended ciphers for TLSv1.2
       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       # Recommended ciphers for TLSv1.3
       - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
       - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
    tlsv13only:
      minVersion: VersionTLS13
http:
  middlewares:
    secure-header:
      headers:
        referrerPolicy: no-referrer
        stsSeconds: 31536000
        forceSTSHeader: true
        stsIncludeSubdomains: true
        browserXssFilter: true
        customRequestHeaders:
          X-Forwarded-Proto: https
